# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiskStartWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiskStartWidget(object):
    def setupUi(self, DiskStartWidget):
        DiskStartWidget.setObjectName("DiskStartWidget")
        DiskStartWidget.resize(1280, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DiskStartWidget.sizePolicy().hasHeightForWidth())
        DiskStartWidget.setSizePolicy(sizePolicy)
        DiskStartWidget.setMinimumSize(QtCore.QSize(1280, 1024))
        DiskStartWidget.setMaximumSize(QtCore.QSize(1280, 1024))
        self.verticalLayoutWidget = QtWidgets.QWidget(DiskStartWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 1021))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setCheckable(False)
        self.backButton.setChecked(False)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_3.addWidget(self.backButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = FileExplorer(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.SaveAsPresetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveAsPresetButton.sizePolicy().hasHeightForWidth())
        self.SaveAsPresetButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SaveAsPresetButton.setFont(font)
        self.SaveAsPresetButton.setObjectName("SaveAsPresetButton")
        self.horizontalLayout.addWidget(self.SaveAsPresetButton)
        self.NextButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextButton.sizePolicy().hasHeightForWidth())
        self.NextButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.horizontalLayout.addWidget(self.NextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DiskStartWidget)
        QtCore.QMetaObject.connectSlotsByName(DiskStartWidget)

    def retranslateUi(self, DiskStartWidget):
        _translate = QtCore.QCoreApplication.translate
        DiskStartWidget.setWindowTitle(_translate("DiskStartWidget", "Form"))
        self.backButton.setText(_translate("DiskStartWidget", "Back"))
        self.SaveAsPresetButton.setText(_translate("DiskStartWidget", "Save As Preset"))
        self.NextButton.setText(_translate("DiskStartWidget", "Next Button"))
from fileexplorer import FileExplorer


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiskStartWidget = QtWidgets.QWidget()
    ui = Ui_DiskStartWidget()
    ui.setupUi(DiskStartWidget)
    DiskStartWidget.show()
    sys.exit(app.exec_())
