# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileStart.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileStartWidget(object):
    def setupUi(self, FileStartWidget):
        FileStartWidget.setObjectName("FileStartWidget")
        FileStartWidget.resize(1280, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileStartWidget.sizePolicy().hasHeightForWidth())
        FileStartWidget.setSizePolicy(sizePolicy)
        FileStartWidget.setMinimumSize(QtCore.QSize(1280, 1024))
        FileStartWidget.setMaximumSize(QtCore.QSize(1280, 1024))
        self.horizontalLayoutWidget = QtWidgets.QWidget(FileStartWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 1021))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.presetName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.presetName.setObjectName("presetName")
        self.verticalLayout_3.addWidget(self.presetName)
        self.presetDetails = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.presetDetails.setObjectName("presetDetails")
        self.verticalLayout_3.addWidget(self.presetDetails)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphPreviewWidget = QChartView(self.horizontalLayoutWidget)
        self.graphPreviewWidget.setObjectName("graphPreviewWidget")
        self.horizontalLayout_3.addWidget(self.graphPreviewWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.backButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(FileStartWidget)
        QtCore.QMetaObject.connectSlotsByName(FileStartWidget)

    def retranslateUi(self, FileStartWidget):
        _translate = QtCore.QCoreApplication.translate
        FileStartWidget.setWindowTitle(_translate("FileStartWidget", "Form"))
        self.presetName.setText(_translate("FileStartWidget", "Working File Name"))
        self.presetDetails.setText(_translate("FileStartWidget", "Working File Details \n"
"eg: Run Time, Max Temp, Max Pressure, User Notes, Last Time Ran, "))
        self.pushButton_2.setText(_translate("FileStartWidget", "Back"))
        self.backButton.setText(_translate("FileStartWidget", "START"))
from qchartview import QChartView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FileStartWidget = QtWidgets.QWidget()
    ui = Ui_FileStartWidget()
    ui.setupUi(FileStartWidget)
    FileStartWidget.show()
    sys.exit(app.exec_())
